### ISSUE TITLE
[Feature request] Compiled dll like you did with AVIF plugin

### ISSUE THREAD

**Issue by paconaranjo** [novomesk/qt-heic-image-plugin#1]
Thanks for your hard work!

**Comment by novomesk** [comment]
Hello,
can you tell me for what application you need the DLL?

Because qavif.dll was built to be used with nomacs and nomacs has already qheif.dll plug-in. It is an alternative/third-party implementation (built from qt-heif-image-plugin sources) but it is able to open HEIF/HEIC files too.

**Comment by paconaranjo** [comment]
Hi, I wanted for Quickviewer:
https://kanryu.github.io/quickviewer/

Thanks.

**Comment by novomesk** [comment]
Problem is that kanryu quickviewer uses old Qt 5.12 but this plug-in needs at least Qt 5.14 because it has color profiles support.

I can work in the future if Windows quickviewer is rebuilt to use the newer Qt.

**Comment by paconaranjo** [comment]
What about better plug-in for:
https://interversehq.com/qview/

**Comment by novomesk** [comment]
> What about better plug-in for:
> https://interversehq.com/qview/

The application in qView-4.0-win64.zip also uses only Qt 5.12.9 but if you install [MSYS2](https://www.msys2.org/) you can conveniently build qView and plug-ins in the same environment.

**Comment by novomesk** [comment]
I think recent qView already use the plug-in.
